export type Game = {
  id: string;
  name: string;
  link?: string;
  android?: string;
  play?: string;
  ios?: string;
  image: string;
  tag?: string;
  rating?: string;
};
export const TopGames: Game[] = [
  {
    id: "1",
    name: "Game Vault",
    link: "https://download.gamevault999.com/",
    android: "",
    ios: "",
    image: "/images/vault.png",
    tag: "Popular",
    rating: "4.5",
  },
  {
    id: "2",
    name: "Lasvegas Sweeps",
    link: "https://m.lasvegassweeps.com/",
    android: "",
    ios: "",
    image: "/images/vegas.png",
    tag: "Trending",
    rating: "4.3",
  },
  {
    id: "3",
    name: "Juwa City",
    link: "https://dl.juwa777.com/",
    android: "",
    ios: "",
    image: "/images/juwa.png",
    tag: "Featured",
    rating: "4.4",
  },
  {
    id: "4",
    name: "Loot Game",
    link: "http://m.lootgame777.com/",
    android: "",
    ios: "",
    image: "/images/loot.jpg",
    tag: "Arcade",
    rating: "4.6",
  },
  {
    id: "5",
    name: "Orion Star",
    link: "http://web.orionstars.vip/play/orionstars/",
    android: "",
    ios: "",
    image: "/images/vault.png",
    tag: "New",
    rating: "4.2",
  },
  {
    id: "6",
    name: "Milky Way App",
    link: "https://milkywayapp.xyz/",
    android: "",
    ios: "",
    image: "/images/milky.jpg",
    tag: "Casino",
    rating: "4.5",
  },
  {
    id: "7",
    name: "Fire Kirin",
    link: "https://firekirin.com/",
    android: "",
    ios: "",
    image: "/images/fire.jpg",
    tag: "Top Rated",
    rating: "4.7",
  },
  {
    id: "8",
    name: "Panda Master",
    link: "https://pandamaster.vip:8888/index.html",
    android: "",
    ios: "",
    image: "/images/panda.jpg",
    tag: "Casino",
    rating: "4.6",
  },
  {
    id: "9",
    name: "Mr All In One",
    link: "https://www.mrallinone777.com/m",
    android: "",
    ios: "",
    image: "/images/mr..webp",
    tag: "Hot",
    rating: "4.4",
  },
  {
    id: "10",
    name: "Cash Machine",
    link: "https://www.cashmachine777.com/m",
    android: "",
    ios: "",
    image: "/images/cashmachine.webp",
    tag: "Casino",
    rating: "4.2",
  },
  {
    id: "11",
    name: "Casino Royal",
    link: "http://m.casinoroyale07.com/",
    android: "",
    ios: "",
    image: "/images/vault.png",
    tag: "Casino",
    rating: "4.3",
  },
];

export const hotGames: Game[] = [
  {
    id: "12",
    name: "High Roller",
    link: "https://www.highrollerdownload.com/",
    android: "",
    ios: "",
    image: "/images/high.jpg",
    tag: "High Stakes",
    rating: "4.1",
  },
  {
    id: "13",
    name: "Vb Link",
    link: "https://www.vblink777.club",
    android: "",
    ios: "",
    image: "/images/vault.png",
    tag: "Arcade",
    rating: "4.5",
  },
  {
    id: "14",
    name: "Fish Thunder",
    link: "https://www.fishthunder.online/login",
    android: "",
    ios: "",
    image: "/images/fire.jpg",
    tag: "Adventure",
    rating: "4.2",
  },
  {
    id: "15",
    name: "Vegas Strip",
    link: "https://www.vegasstrip.online/login",
    android: "",
    ios: "",
    image: "/images/vegas.png",
    tag: "Vegas",
    rating: "4.3",
  },
  {
    id: "16",
    name: "Candy Land",
    link: "https://www.candyland.mobi/login",
    android: "",
    ios: "",
    image: "/images/milky.jpg",
    tag: "Fun",
    rating: "4.0",
  },
  {
    id: "17",
    name: "Euro Vegas 7",
    link: "https://eurovegas7.com/login",
    android: "",
    ios: "",
    image: "/images/vegas.png",
    tag: "Vegas",
    rating: "4.4",
  },
  {
    id: "18",
    name: "Game Room",
    link: "https://www.gameroom777.com/m",
    android: "",
    ios: "",
    image: "/images/gameroom.webp",
    tag: "Arcade",
    rating: "4.2",
  },
  {
    id: "19",
    name: "River Sweep",
    link: "https://river777.com/android.html",
    android: "",
    ios: "",
    image: "/images/vault.png",
    tag: "Casino",
    rating: "4.3",
  },
  {
    id: "20",
    name: "Blue Dragon",
    link: "https://app.bluedragon777.com",
    android: "",
    ios: "",
    image: "/images/noble.webp",
    tag: "Fantasy",
    rating: "4.5",
  },
  {
    id: "21",
    name: "King of Pop",
    link: "https://www.slots88888.com",
    android: "",
    ios: "",
    image: "/images/vault.png",
    tag: "Music",
    rating: "4.1",
  },
  {
    id: "22",
    name: "Vega X",
    link: "https://cashier.vegas-x.org/",
    android: "",
    ios: "",
    image: "/images/vault.png",
    tag: "Vegas",
    rating: "4.2",
  },
];
